# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tCHdr2fKAREap2nmFnL2SQ-lS7kYLcle

### Cálculo de Utilidad Final Disponible

Este notebook calculará la utilidad final disponible a partir de una rentabilidad neta, aplicando deducciones por seguridad social, gastos educativos y el impacto del IVA. Se presentará un desglose detallado de los gastos, la rentabilidad real y una proyección de ahorro neto anual.
"""

# 1. Parámetros iniciales
rentabilidad_neta_inicial = 400000000  # Rentabilidad neta generada por las 5 unidades de negocio

print(f"Rentabilidad Neta Inicial: {rentabilidad_neta_inicial:,.2f}")

# 2. Deducción por Seguridad Social en Salud
# Se asume una 'base gravable' del 70% de la rentabilidad neta para el cálculo de seguridad social.
# Esta es una suposición para el ejemplo, ya que la base real dependería de la legislación específica y el régimen tributario.
porcentaje_seguridad_social = 0.07
base_gravable_seguridad_social = rentabilidad_neta_inicial * 0.70 # Asunción

deduccion_seguridad_social = base_gravable_seguridad_social * porcentaje_seguridad_social

print(f"Base Gravable para Seguridad Social (70%): {base_gravable_seguridad_social:,.2f}")
print(f"Deducción por Seguridad Social (7%): {deduccion_seguridad_social:,.2f}")

# 3. Gastos Educativos Anuales

# Mensualidades escolares (2 hijos * 1.000.000 * 10 meses)
gastos_escolares_anuales = 2 * 1000000 * 10

# Matrícula universitaria (1 hijo * 32.000.000 * 2 semestres)
gastos_universitarios_anuales = 1 * 32000000 * 2

gastos_educativos_anuales = gastos_escolares_anuales + gastos_universitarios_anuales

print(f"Gastos Escolares Anuales: {gastos_escolares_anuales:,.2f}")
print(f"Gastos Universitarios Anuales: {gastos_universitarios_anuales:,.2f}")
print(f"Gastos Educativos Totales Anuales: {gastos_educativos_anuales:,.2f}")

# 4. Impacto del IVA del 19% sobre el excedente de consumo estimado

# Primero, calculamos el ingreso disponible antes del IVA
ingreso_despues_deducciones_fijas = rentabilidad_neta_inicial - deduccion_seguridad_social - gastos_educativos_anuales

# Se asume que el 'excedente de consumo estimado' es un 30% del ingreso disponible después de las deducciones fijas.
# Esta es una suposición para el ejemplo.
porcentaje_excedente_consumo = 0.30
excedente_consumo_estimado = ingreso_despues_deducciones_fijas * porcentaje_excedente_consumo

porcentaje_iva = 0.19
impacto_iva = excedente_consumo_estimado * porcentaje_iva

print(f"Ingreso Disponible antes de IVA: {ingreso_despues_deducciones_fijas:,.2f}")
print(f"Excedente de Consumo Estimado (30%): {excedente_consumo_estimado:,.2f}")
print(f"Impacto del IVA (19%): {impacto_iva:,.2f}")

# 5. Cálculo de Utilidad Final Disponible y métricas adicionales

total_deducciones = deduccion_seguridad_social + gastos_educativos_anuales + impacto_iva
utilidad_final_disponible = rentabilidad_neta_inicial - total_deducciones

# Desglose detallado de gastos frente a ingresos
print("\n--- Desglose Detallado ---")
print(f"Rentabilidad Neta Inicial: {rentabilidad_neta_inicial:,.2f}")
print(f"  - Deducción Seguridad Social (7% sobre base gravable del 70%): {deduccion_seguridad_social:,.2f}")
print(f"  - Gastos Educativos Anuales: {gastos_educativos_anuales:,.2f}")
print(f"  - Impacto IVA (19% sobre 30% del excedente de consumo): {impacto_iva:,.2f}")
print(f"Total Deducciones: {total_deducciones:,.2f}")
print(f"\nUtilidad Final Disponible: {utilidad_final_disponible:,.2f}")

# Porcentaje de rentabilidad real tras costos fijos familiares
porcentaje_rentabilidad_real = (utilidad_final_disponible / rentabilidad_neta_inicial) * 100
print(f"\nPorcentaje de Rentabilidad Real (después de costos familiares): {porcentaje_rentabilidad_real:,.2f}%")

# Proyección de ahorro neto anual para reinversión
# Se asume que toda la utilidad final disponible puede ser considerada ahorro neto para reinversión,
# o se podría definir un porcentaje de esta.
ahorro_neto_anual_reinversion = utilidad_final_disponible
print(f"\nProyección de Ahorro Neto Anual para Reinversión: {ahorro_neto_anual_reinversion:,.2f}")

"""### Resumen de Resultados

La rentabilidad neta inicial de **$400,000,000** se ajusta por las siguientes deducciones:

*   **Seguridad Social en Salud:** ${deduccion_seguridad_social:,.2f}
*   **Gastos Educativos Anuales:** ${gastos_educativos_anuales:,.2f}
*   **Impacto del IVA (sobre excedente de consumo estimado):** ${impacto_iva:,.2f}

La **Utilidad Final Disponible** es de **${utilidad_final_disponible:,.2f}**, lo que representa una **Rentabilidad Real** del **{porcentaje_rentabilidad_real:,.2f}%** sobre la rentabilidad neta inicial. Este monto (${ahorro_neto_anual_reinversion:,.2f}) puede considerarse como el **Ahorro Neto Anual disponible para Reinversión**.
"""