# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Njo7OISObviDM2TE2nPIkmmN0U3HZBx8
"""

!pip install yfinance pandas numpy matplotlib seaborn

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

# Parámetros iniciales
capital_inicial = 3000
comision_broker = 0.001
rendimiento_anual_local = 0.08
meses_inversion = 12

# Descarga de datos
tickers = ['EURUSD=X', 'GBPUSD=X', 'USDCOP=X']
data = yf.download(tickers, period='2y')['Close']

# Ajuste para COP: yfinance entrega USDCOP, necesitamos COPUSD para evaluar inversión desde USD
data['COPUSD=X'] = 1 / data['USDCOP=X']
assets = ['EURUSD=X', 'GBPUSD=X', 'COPUSD=X']
prices = data[assets].dropna()

display(prices.tail())

# Análisis Estadístico y Volatilidad
returns = np.log(prices / prices.shift(1)).dropna()
volatilidad_anual = returns.std() * np.sqrt(252)

print("Volatilidad Anualizada:")
print(volatilidad_anual)

# Simulación de Monte Carlo
num_simulaciones = 10000
# Proyección a Abril 2027 (aprox 3 años desde hoy)
dias_proyeccion = (datetime(2027, 4, 1) - datetime.now()).days

resultados_sim = {}

for asset in assets:
    last_price = prices[asset].iloc[-1]
    mu = returns[asset].mean()
    sigma = returns[asset].std()

    # Simulación de retornos geométricos brownianos
    sim_returns = np.random.normal(mu, sigma, (dias_proyeccion, num_simulaciones))
    price_paths = last_price * np.exp(np.cumsum(sim_returns, axis=0))
    final_prices = price_paths[-1, :]

    # Cálculo de retorno final en USD
    # 1. Comprar divisa (Pagar comisión)
    cantidad_divisa = (capital_inicial * (1 - comision_broker)) * (1 / last_price if 'COP' not in asset else last_price)
    # Nota: yfinance ya da EURUSD (USD por 1 EUR).
    # Para simplificar el cálculo de retorno:
    final_value_usd = final_prices * (capital_inicial / last_price) * (1 - comision_broker * 2) * (1 + rendimiento_anual_local)**(dias_proyeccion/365)

    resultados_sim[asset] = final_value_usd

# Visualización
plt.figure(figsize=(12, 6))
for asset in assets:
    sns.kdeplot(resultados_sim[asset], label=asset, fill=True)
plt.axvline(3000, color='red', linestyle='--', label='Break-even ($3000)')
plt.title('Distribución de Valor Final de la Inversión (Monte Carlo)')
plt.xlabel('Valor Final en USD')
plt.legend()
plt.show()

# Métricas de Salida y Gráfico de Tendencia Histórica
for asset in assets:
    final_vals = resultados_sim[asset]
    prob_perdida = (final_vals < 3000).mean() * 100
    retorno_medio = np.mean(final_vals) - 3000

    current_p = prices[asset].iloc[-1]
    break_even_price = current_p / (1 + rendimiento_anual_local - comision_broker*2)

    print(f"--- Análisis para {asset} ---")
    print(f"Retorno Total Esperado (Promedio): ${retorno_medio:.2f} USD")
    print(f"Probabilidad de Pérdida: {prob_perdida:.2f}%")
    print(f"Precio de Equilibrio (Break-even): {break_even_price:.4f}\n")

# Gráfico de líneas con la tendencia histórica
plt.figure(figsize=(14, 7))
for asset in assets:
    # Normalizamos los precios para comparar la tendencia relativa
    plt.plot(prices[asset] / prices[asset].iloc[0], label=f"{asset} (Normalizado)")

plt.title('Tendencia Histórica de Divisas (Base 1)')
plt.xlabel('Fecha')
plt.ylabel('Precio Relativo')
plt.legend()
plt.grid(True)
plt.show()