# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_vEzv3R3czGQZR_68IN6rAoHYvca138j
"""

import pandas as pd

file_path = '/content/cuentas_fake.xlsx'
df = pd.read_excel(file_path)

display(df.head())

"""### **Simulación Financiera: Crecimiento de AUM y Rentabilidad de Plataforma**

Este script procesará un dataset de 1,000 registros de usuarios para simular el crecimiento del Capital Total Administrado (AUM) y calcular la rentabilidad bruta de la plataforma durante un período de 5 años. Se aplicará una tasa de crecimiento anual compuesta (CAGR) del 5% al AUM y una cuota de manejo anual del 3% sobre el saldo promedio.
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# --- 1. Definición de Parámetros de Simulación ---

# Número de usuarios para la simulación
# Usamos 1000 como se especifica, si el df original tuviera menos, este asegura los 1000.
num_users = 1000

# Tasa de crecimiento anual compuesta (CAGR) del 5%
cagr = 0.05

# Cuota de manejo anual del 3% sobre el saldo promedio
management_fee_rate = 0.03

# Duración de la simulación en años
simulation_years = 5

print(f"Parámetros de simulación:")
print(f"  - Número de usuarios: {num_users}")
print(f"  - CAGR: {cagr*100:.0f}%")
print(f"  - Cuota de manejo: {management_fee_rate*100:.0f}%")
print(f"  - Años de simulación: {simulation_years}")

"""### **2. Preparación de Datos Iniciales para la Simulación**

Para esta simulación, generaremos saldos iniciales aleatorios para 1,000 usuarios. Esto asegura que la simulación cumple con el requisito de `1,000 registros de usuarios`, independientemente del tamaño o estructura del archivo `cuentas_fake.xlsx` cargado previamente.
"""

# Generar saldos iniciales aleatorios para 1000 usuarios
# Los saldos se distribuyen uniformemente entre 1000 y 10000 unidades monetarias.
sim_data = {
    'user_id': range(1, num_users + 1),
    'initial_balance': np.random.uniform(low=1000, high=10000, size=num_users)
}
sim_df = pd.DataFrame(sim_data)

print("Primeros 5 registros de los datos de simulación inicial:")
display(sim_df.head())

"""### **3. Ejecución de la Simulación Financiera**

Se simulará el crecimiento del AUM y se calcularán las comisiones de manejo para cada usuario durante los 5 años. Los resultados anuales se almacenarán para su posterior análisis.
"""

simulation_results = []

current_balances = sim_df['initial_balance'].copy()

for year in range(1, simulation_years + 1):
    # Calcular AUM para el año actual (crecimiento con CAGR)
    current_balances = current_balances * (1 + cagr)

    # Calcular cuota de manejo (3% sobre el saldo promedio anual, que es el current_balances)
    annual_management_fees = current_balances * management_fee_rate

    # Guardar resultados anuales
    simulation_results.append({
        'year': year,
        'total_aum': current_balances.sum(),
        'total_annual_fees': annual_management_fees.sum()
    })

results_df = pd.DataFrame(simulation_results)

print("Resultados anuales de la simulación:")
display(results_df)

"""### **4. Cálculo del Ingreso Total Acumulado por Comisiones**

Aquí se calcula la suma de todas las comisiones generadas a lo largo de los 5 años de simulación.
"""

total_accumulated_commissions = results_df['total_annual_fees'].sum()
print(f"Ingreso total acumulado por comisiones al finalizar el quinto año: ${total_accumulated_commissions:,.2f}")

"""### **5. Visualización: Volumen de Activos vs. Ingresos por Comisiones**

Para facilitar la evaluación de la viabilidad económica, visualizamos cómo evoluciona el AUM total frente a los ingresos anuales por comisiones a lo largo de los 5 años.
"""

fig, ax1 = plt.subplots(figsize=(12, 7))

sns.lineplot(x='year', y='total_aum', data=results_df, marker='o', ax=ax1, color='tab:blue', label='Total AUM')
ax1.set_xlabel('Año')
ax1.set_ylabel('Total AUM (USD)', color='tab:blue')
ax1.tick_params(axis='y', labelcolor='tab:blue')
ax1.set_title('Crecimiento del AUM y Ingresos por Comisiones a 5 años')
ax1.grid(True, linestyle='--', alpha=0.7)

ax2 = ax1.twinx() # Crear un segundo eje Y que comparte el mismo eje X
sns.lineplot(x='year', y='total_annual_fees', data=results_df, marker='x', ax=ax2, color='tab:red', label='Ingresos por Comisiones')
ax2.set_ylabel('Ingresos por Comisiones (USD)', color='tab:red')
ax2.tick_params(axis='y', labelcolor='tab:red')

# Combinar leyendas de ambos ejes
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')

plt.xticks(results_df['year'])
plt.tight_layout()
plt.show()